name: wnews
description: A tiny command-line newsreader backed by Wikipedia.
version: 0.2.2
repository: https://github.com/filiph/wnews

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.3.1
  html: ^0.15.4
  intl: ^0.18.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0

executables:
  wnews:
